import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import MenuBar from '@/components/MenuBar';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['500'],
});

export const metadata: Metadata = {
	title: 'Furniro',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<MenuBar />
				{children}
			</body>
		</html>
	);
}
